---
deployment:
  tasks:
    - /bin/cp index.html /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/cp -r images /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/bio
    - /bin/cp bio/index.html /home/ntpsrnlfrg/anonimustradelive.com/bio/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/herramientas
    - /bin/cp herramientas/index.html /home/ntpsrnlfrg/anonimustradelive.com/herramientas/
    - /bin/cp kofi-webhook.php /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/cp crypto-donors.php /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/cp telegram-notify.php /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/test -f /home/ntpsrnlfrg/anonimustradelive.com/donors.json || /bin/cp donors.json /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/cp gate.php /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/cp verify.php /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/cp telegram-auth-webhook.php /home/ntpsrnlfrg/anonimustradelive.com/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/commands
    - /bin/cp commands/start.php /home/ntpsrnlfrg/anonimustradelive.com/commands/
    - /bin/cp commands/acceso.php /home/ntpsrnlfrg/anonimustradelive.com/commands/
    - /bin/cp commands/libros.php /home/ntpsrnlfrg/anonimustradelive.com/commands/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/utilidades
    - /bin/rm -f /home/ntpsrnlfrg/anonimustradelive.com/utilidades/index.html
    - /bin/cp utilidades/index.php /home/ntpsrnlfrg/anonimustradelive.com/utilidades/
    - /bin/cp utilidades/.htaccess /home/ntpsrnlfrg/anonimustradelive.com/utilidades/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/ads
    - /bin/cp ads/index.html /home/ntpsrnlfrg/anonimustradelive.com/ads/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/ads/ads_img
    - /bin/cp -r ads/ads_img /home/ntpsrnlfrg/anonimustradelive.com/ads/
    - /bin/mkdir -p /home/ntpsrnlfrg/anonimustradelive.com/libros
    - /bin/cp libros/index.html /home/ntpsrnlfrg/anonimustradelive.com/libros/
    - /bin/mkdir -p /home/ntpsrnlfrg/reg.anonimustradelive.com
    - /bin/cp reg/webhook.php /home/ntpsrnlfrg/reg.anonimustradelive.com/
    - /bin/cp reg/index.php /home/ntpsrnlfrg/reg.anonimustradelive.com/
    - /bin/cp reg/login.php /home/ntpsrnlfrg/reg.anonimustradelive.com/
    - /bin/cp reg/logout.php /home/ntpsrnlfrg/reg.anonimustradelive.com/
    - /bin/cp reg/setup.php /home/ntpsrnlfrg/reg.anonimustradelive.com/
